import { Theme } from '../theme-types';

export const PRESET_THEMES: Record<string, Theme> = {
  'wechat-default': {
    name: '默认公众号',
    styles: {
      container: 'max-width: 740px; margin: 0 auto; padding: 10px 12px 20px 12px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.8 !important; color: #3f3f3f !important; background-color: #fff !important; word-wrap: break-word;',
      h1: 'font-size: 24px; font-weight: 600; color: #2c3e50 !important; line-height: 1.4 !important; margin: 32px 0 16px; padding-bottom: 8px; border-bottom: 2px solid #3498db;',
      h2: 'font-size: 22px; font-weight: 600; color: #2c3e50 !important; line-height: 1.4 !important; margin: 28px 0 14px; padding-left: 12px; border-left: 4px solid #3498db;',
      h3: 'font-size: 20px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      h4: 'font-size: 18px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 20px 0 10px;',
      h5: 'font-size: 17px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 18px 0 9px;',
      h6: 'font-size: 16px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 16px 0 8px;',
      p: 'margin: 16px 0 !important; line-height: 1.8 !important; color: #3f3f3f !important;',
      strong: 'font-weight: 600; color: #2c3e50 !important;',
      em: 'font-style: italic; color: #555 !important;',
      a: 'color: #3498db !important; text-decoration: none; border-bottom: 1px solid #3498db;',
      ul: 'margin: 16px 0; padding-left: 24px;',
      ol: 'margin: 16px 0; padding-left: 24px;',
      li: 'margin: 8px 0; line-height: 1.8 !important;',
      blockquote: 'margin: 16px 0; padding: 8px 16px; background-color: #fafafa !important; border-left: 3px solid #999; color: #666 !important; line-height: 1.5 !important;',
      code: 'font-family: Consolas, Monaco, "Courier New", monospace; font-size: 14px; padding: 2px 6px; background-color: #f5f5f5 !important; color: #e74c3c !important; border-radius: 3px;',
      pre: 'margin: 20px 0; padding: 16px; background-color: #2d2d2d !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 32px 0; border: none; border-top: 1px solid #e0e0e0;',
      img: 'max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 20px auto; border-radius: 8px;',
      table: 'width: 100%; margin: 20px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f0f0f0 !important; padding: 10px; text-align: left; border: 1px solid #e0e0e0; font-weight: 600;',
      td: 'padding: 10px; border: 1px solid #e0e0e0;',
      tr: 'border-bottom: 1px solid #e0e0e0;',
    }
  },

  'wechat-tech': {
    name: '技术风格',
    styles: {
      container: 'max-width: 740px; margin: 0 auto; padding: 10px 12px 20px 12px; font-family: "SF Pro Text", -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif; font-size: 16px; line-height: 1.8 !important; color: #333 !important; background-color: #fff !important; word-wrap: break-word;',
      h1: 'font-size: 26px; font-weight: 700; color: #0066cc !important; line-height: 1.3 !important; margin: 36px 0 18px; border-bottom: 2px solid #0066cc; padding-bottom: 10px;',
      h2: 'font-size: 22px; font-weight: 700; color: #0066cc !important; line-height: 1.3 !important; margin: 30px 0 14px; border-left: 4px solid #0066cc; padding-left: 12px; background: #f0f7ff; padding: 8px 12px;',
      h3: 'font-size: 20px; font-weight: 600; color: #1a6699 !important; line-height: 1.3 !important; margin: 24px 0 12px;',
      h4: 'font-size: 18px; font-weight: 600; color: #1a6699 !important; line-height: 1.3 !important; margin: 20px 0 10px;',
      h5: 'font-size: 17px; font-weight: 600; color: #1a6699 !important; line-height: 1.3 !important; margin: 18px 0 9px;',
      h6: 'font-size: 16px; font-weight: 600; color: #1a6699 !important; line-height: 1.3 !important; margin: 16px 0 8px;',
      p: 'margin: 16px 0 !important; line-height: 1.8 !important; color: #333 !important;',
      strong: 'font-weight: 700; color: #0066cc !important;',
      em: 'font-style: italic; color: #555 !important;',
      a: 'color: #0066cc !important; text-decoration: none; border-bottom: 1px dashed #0066cc;',
      ul: 'margin: 16px 0; padding-left: 24px;',
      ol: 'margin: 16px 0; padding-left: 24px;',
      li: 'margin: 8px 0; line-height: 1.8 !important;',
      blockquote: 'margin: 16px 0; padding: 12px 16px; background-color: #f0f7ff !important; border-left: 4px solid #0066cc; color: #333 !important; border-radius: 0 6px 6px 0;',
      code: 'font-family: "SF Mono", Consolas, Monaco, "Courier New", monospace; font-size: 13px; padding: 2px 6px; background-color: #f0f7ff !important; color: #0066cc !important; border-radius: 3px; border: 1px solid #cce0ff;',
      pre: 'margin: 20px 0; padding: 16px; background-color: #1e1e2e !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 32px 0; border: none; border-top: 2px dashed #0066cc; opacity: 0.3;',
      img: 'max-width: 100%; height: auto; display: block; margin: 20px auto; border-radius: 4px; border: 1px solid #e0e8f0;',
      table: 'width: 100%; margin: 20px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #0066cc !important; color: #fff !important; padding: 10px 12px; text-align: left; font-weight: 600;',
      td: 'padding: 10px 12px; border: 1px solid #e0e0e0;',
      tr: 'border-bottom: 1px solid #e0e0e0;',
    }
  },

  'latepost-depth': {
    name: '晚点风格',
    styles: {
      container: 'max-width: 740px; margin: 0 auto; padding: 10px 12px 20px 12px; font-family: "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Noto Serif SC", Georgia, serif; font-size: 17px; line-height: 1.9 !important; color: #1a1a1a !important; background-color: #fff !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 700; color: #d32f2f !important; line-height: 1.3 !important; margin: 40px 0 20px; letter-spacing: -0.5px;',
      h2: 'font-size: 22px; font-weight: 700; color: #1a1a1a !important; line-height: 1.3 !important; margin: 32px 0 16px; padding-bottom: 8px; border-bottom: 2px solid #d32f2f;',
      h3: 'font-size: 20px; font-weight: 600; color: #333 !important; line-height: 1.3 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #333 !important; line-height: 1.3 !important; margin: 24px 0 12px;',
      h5: 'font-size: 17px; font-weight: 600; color: #333 !important; line-height: 1.3 !important; margin: 20px 0 10px;',
      h6: 'font-size: 16px; font-weight: 600; color: #333 !important; line-height: 1.3 !important; margin: 18px 0 9px;',
      p: 'margin: 18px 0 !important; line-height: 1.9 !important; color: #1a1a1a !important;',
      strong: 'font-weight: 700; color: #d32f2f !important;',
      em: 'font-style: italic; color: #555 !important;',
      a: 'color: #d32f2f !important; text-decoration: none; border-bottom: 1px solid #d32f2f;',
      ul: 'margin: 18px 0; padding-left: 24px;',
      ol: 'margin: 18px 0; padding-left: 24px;',
      li: 'margin: 10px 0; line-height: 1.9 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; border-left: 4px solid #d32f2f; background-color: #fafafa !important; color: #555 !important; font-style: italic; line-height: 1.8 !important;',
      code: 'font-family: "SF Mono", Consolas, Monaco, monospace; font-size: 14px; padding: 2px 6px; background-color: #f5f5f5 !important; color: #d32f2f !important; border-radius: 3px;',
      pre: 'margin: 24px 0; padding: 16px; background-color: #1a1a1a !important; border-radius: 4px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 40px 0; border: none; border-top: 1px solid #e0e0e0;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f5f5f5 !important; padding: 12px; text-align: left; border-bottom: 2px solid #d32f2f; font-weight: 600;',
      td: 'padding: 12px; border-bottom: 1px solid #e0e0e0;',
      tr: 'border-bottom: 1px solid #e0e0e0;',
    }
  },

  'wechat-anthropic': {
    name: 'Claude 风格',
    styles: {
      container: 'max-width: 740px; margin: 0 auto; padding: 10px 12px 20px 12px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; font-size: 16px; line-height: 1.8 !important; color: #3d2b1f !important; background-color: #faf8f5 !important; word-wrap: break-word;',
      h1: 'font-size: 26px; font-weight: 700; background: linear-gradient(135deg, #C15F3C, #e8854d); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; line-height: 1.3 !important; margin: 36px 0 18px;',
      h2: 'font-size: 22px; font-weight: 600; color: #C15F3C !important; line-height: 1.3 !important; margin: 28px 0 14px; padding-left: 12px; border-left: 4px solid #C15F3C;',
      h3: 'font-size: 20px; font-weight: 600; color: #a04a2a !important; line-height: 1.3 !important; margin: 24px 0 12px;',
      h4: 'font-size: 18px; font-weight: 600; color: #a04a2a !important; line-height: 1.3 !important; margin: 20px 0 10px;',
      h5: 'font-size: 17px; font-weight: 600; color: #a04a2a !important; line-height: 1.3 !important; margin: 18px 0 9px;',
      h6: 'font-size: 16px; font-weight: 600; color: #a04a2a !important; line-height: 1.3 !important; margin: 16px 0 8px;',
      p: 'margin: 16px 0 !important; line-height: 1.8 !important; color: #3d2b1f !important;',
      strong: 'font-weight: 700; color: #C15F3C !important;',
      em: 'font-style: italic; color: #7a5040 !important;',
      a: 'color: #C15F3C !important; text-decoration: none; border-bottom: 1px solid #C15F3C;',
      ul: 'margin: 16px 0; padding-left: 24px;',
      ol: 'margin: 16px 0; padding-left: 24px;',
      li: 'margin: 8px 0; line-height: 1.8 !important;',
      blockquote: 'margin: 16px 0; padding: 12px 20px; background-color: #f5ede8 !important; border-left: 4px solid #C15F3C; color: #5a3826 !important; border-radius: 0 8px 8px 0;',
      code: 'font-family: "SF Mono", Consolas, Monaco, monospace; font-size: 14px; padding: 2px 6px; background-color: #f5ede8 !important; color: #C15F3C !important; border-radius: 3px;',
      pre: 'margin: 20px 0; padding: 16px; background-color: #2d2420 !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 32px 0; border: none; border-top: 1px solid #e8d5c8;',
      img: 'max-width: 100%; height: auto; display: block; margin: 20px auto; border-radius: 8px;',
      table: 'width: 100%; margin: 20px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f5ede8 !important; padding: 10px; text-align: left; border: 1px solid #e8d5c8; font-weight: 600; color: #C15F3C !important;',
      td: 'padding: 10px; border: 1px solid #e8d5c8;',
      tr: 'border-bottom: 1px solid #e8d5c8;',
    }
  },

  'wechat-ft': {
    name: '金融时报',
    styles: {
      container: 'max-width: 740px; margin: 0 auto; padding: 10px 12px 20px 12px; font-family: Georgia, "Times New Roman", "Noto Serif SC", serif; font-size: 17px; line-height: 1.9 !important; color: #333 !important; background-color: #fff1e5 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #1a1a1a !important; line-height: 1.2 !important; margin: 40px 0 20px; font-family: Georgia, serif;',
      h2: 'font-size: 24px; font-weight: 700; color: #1a1a1a !important; line-height: 1.3 !important; margin: 32px 0 16px; font-family: Georgia, serif;',
      h3: 'font-size: 20px; font-weight: 700; color: #990f3d !important; line-height: 1.3 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 700; color: #990f3d !important; line-height: 1.3 !important; margin: 24px 0 12px;',
      h5: 'font-size: 17px; font-weight: 700; color: #990f3d !important; line-height: 1.3 !important; margin: 20px 0 10px;',
      h6: 'font-size: 16px; font-weight: 700; color: #990f3d !important; line-height: 1.3 !important; margin: 18px 0 9px;',
      p: 'margin: 18px 0 !important; line-height: 1.9 !important; color: #333 !important;',
      strong: 'font-weight: 700; color: #1a1a1a !important;',
      em: 'font-style: italic; color: #555 !important;',
      a: 'color: #990f3d !important; text-decoration: none; border-bottom: 1px solid #990f3d;',
      ul: 'margin: 18px 0; padding-left: 24px;',
      ol: 'margin: 18px 0; padding-left: 24px;',
      li: 'margin: 10px 0; line-height: 1.9 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; border-left: 4px solid #990f3d; background-color: #fde8e8 !important; color: #333 !important; font-style: italic;',
      code: 'font-family: "SF Mono", Consolas, Monaco, monospace; font-size: 14px; padding: 2px 6px; background-color: #e8e0d8 !important; color: #990f3d !important; border-radius: 3px;',
      pre: 'margin: 24px 0; padding: 16px; background-color: #1a1a1a !important; border-radius: 4px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 40px 0; border: none; border-top: 2px solid #990f3d; opacity: 0.4;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #990f3d !important; color: #fff !important; padding: 10px; text-align: left; font-weight: 700;',
      td: 'padding: 10px; border: 1px solid #e0cfc0;',
      tr: 'border-bottom: 1px solid #e0cfc0;',
    }
  },

  'wechat-elegant': {
    name: '优雅衬线',
    styles: {
      container: 'max-width: 740px; margin: 0 auto; padding: 10px 12px 20px 12px; font-family: "Noto Serif SC", "SimSun", Georgia, serif; font-size: 17px; line-height: 2 !important; color: #2c2c2c !important; background-color: #fff !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 700; color: #1a1a1a !important; line-height: 1.4 !important; margin: 40px 0 20px; text-align: center; letter-spacing: 2px;',
      h2: 'font-size: 22px; font-weight: 700; color: #1a1a1a !important; line-height: 1.4 !important; margin: 32px 0 16px; text-align: center; letter-spacing: 1px;',
      h3: 'font-size: 20px; font-weight: 600; color: #333 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #333 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      h5: 'font-size: 17px; font-weight: 600; color: #333 !important; line-height: 1.4 !important; margin: 20px 0 10px;',
      h6: 'font-size: 16px; font-weight: 600; color: #333 !important; line-height: 1.4 !important; margin: 18px 0 9px;',
      p: 'margin: 18px 0 !important; line-height: 2 !important; color: #2c2c2c !important; text-indent: 2em;',
      strong: 'font-weight: 700; color: #1a1a1a !important;',
      em: 'font-style: italic; color: #555 !important;',
      a: 'color: #333 !important; text-decoration: underline;',
      ul: 'margin: 18px 0; padding-left: 24px;',
      ol: 'margin: 18px 0; padding-left: 24px;',
      li: 'margin: 10px 0; line-height: 2 !important;',
      blockquote: 'margin: 24px 40px; padding: 16px; border: 1px solid #ccc; color: #555 !important; font-style: italic; background-color: #fafafa !important;',
      code: 'font-family: "SF Mono", Consolas, Monaco, monospace; font-size: 14px; padding: 2px 6px; background-color: #f5f5f5 !important; color: #333 !important; border-radius: 3px;',
      pre: 'margin: 24px 0; padding: 16px; background-color: #2d2d2d !important; border-radius: 4px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 40px auto; border: none; border-top: 1px solid #ccc; width: 60%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f0f0f0 !important; padding: 10px; text-align: center; border: 1px solid #ccc; font-weight: 600;',
      td: 'padding: 10px; border: 1px solid #ccc; text-align: center;',
      tr: 'border-bottom: 1px solid #ccc;',
    }
  },

  'warm-docs': {
    name: '焦橙文档',
    styles: {
      container: 'max-width: 740px; margin: 0 auto; padding: 10px 12px 20px 12px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; font-size: 16px; line-height: 1.8 !important; color: #1c1917 !important; background-color: #FAFAF9 !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 700; color: #C2410C !important; line-height: 1.3 !important; margin: 40px 0 20px; border-bottom: 2px solid #fdba74; padding-bottom: 10px;',
      h2: 'font-size: 22px; font-weight: 700; color: #9a3412 !important; line-height: 1.3 !important; margin: 32px 0 16px; padding-left: 12px; border-left: 4px solid #C2410C;',
      h3: 'font-size: 20px; font-weight: 600; color: #7c2d12 !important; line-height: 1.3 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #7c2d12 !important; line-height: 1.3 !important; margin: 24px 0 12px;',
      h5: 'font-size: 17px; font-weight: 600; color: #7c2d12 !important; line-height: 1.3 !important; margin: 20px 0 10px;',
      h6: 'font-size: 16px; font-weight: 600; color: #7c2d12 !important; line-height: 1.3 !important; margin: 18px 0 9px;',
      p: 'margin: 16px 0 !important; line-height: 1.8 !important; color: #1c1917 !important;',
      strong: 'font-weight: 700; color: #C2410C !important;',
      em: 'font-style: italic; color: #78350f !important;',
      a: 'color: #C2410C !important; text-decoration: none; border-bottom: 1px solid #fdba74;',
      ul: 'margin: 16px 0; padding-left: 24px;',
      ol: 'margin: 16px 0; padding-left: 24px;',
      li: 'margin: 8px 0; line-height: 1.8 !important;',
      blockquote: 'margin: 20px 0; padding: 12px 16px; background-color: #fff7ed !important; border-left: 4px solid #C2410C; color: #78350f !important; border-radius: 0 6px 6px 0;',
      code: 'font-family: "SF Mono", Consolas, Monaco, monospace; font-size: 14px; padding: 2px 6px; background-color: #fff7ed !important; color: #C2410C !important; border-radius: 3px; border: 1px solid #fed7aa;',
      pre: 'margin: 20px 0; padding: 16px; background-color: #1c1917 !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important;',
      hr: 'margin: 32px 0; border: none; border-top: 2px solid #fed7aa;',
      img: 'max-width: 100%; height: auto; display: block; margin: 20px auto; border-radius: 6px;',
      table: 'width: 100%; margin: 20px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #fff7ed !important; padding: 10px; text-align: left; border: 1px solid #fed7aa; font-weight: 600; color: #C2410C !important;',
      td: 'padding: 10px; border: 1px solid #fed7aa;',
      tr: 'border-bottom: 1px solid #fed7aa;',
    }
  },
};
