import esbuild from "esbuild";
import fs from "fs/promises";
import path from "path";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit https://github.com/Jackywxsz/MD_flow
*/
`;

const prod = (process.argv[2] === "production");

// In dev mode, output directly to vault plugin directory for hot-reload
const vaultPluginDir = "/Users/jackyjia/Library/Mobile Documents/iCloud~md~obsidian/Documents/.obsidian/plugins/mdflow-publisher";
const outfile = prod ? "main.js" : `${vaultPluginDir}/main.js`;
const outputDir = prod ? process.cwd() : vaultPluginDir;

async function copyPluginAssets() {
	await fs.copyFile("src/styles.css", path.join(outputDir, "styles.css"));
	await fs.copyFile("manifest.json", path.join(outputDir, "manifest.json"));
}

const assetPlugin = {
	name: "copy-plugin-assets",
	setup(build) {
		build.onStart(async () => {
			await copyPluginAssets();
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile,
	plugins: [assetPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
